defmodule Pokerap do

  @moduledoc """
  Pokerap: This is the main module that you'll find all of the methods to
  call resources from the Pokeapi http://pokeapi.co/
  """
  require Pokerap.Macro

  # Macro to define functions for generic endpoints
  ["berry", "berry_firmness", "berry_flavor", "contest_type",
   "contest_effect", "super_contest_effect", "encounter_method",
   "encounter_condition", "encounter_condition_value", "evolution_chain",
   "evolution_trigger", "generation", "pokedex", "version", "version_group",
   "item", "item_attribute", "item_category", "item_fling_effect",
   "item_pocket", "machine", "move", "move_ailment", "move_battle_style",
   "move_category", "move_damage_class", "move_learn_method", "move_target",
   "location", "location_area", "pal_park_area", "region", "ability",
   "characteristic", "egg_group", "gender", "growth_rate", "nature",
   "pokeathlon_stat", "pokemon", "pokemon_color", "pokemon_form",
   "pokemon_habitat", "pokemon_shape", "pokemon_species", "stat",
   "type", "language"]
   |> Pokerap.Macro.make_endpoint_calls

end

defmodule Pokerap.InMemory do
  @moduledoc ~S"""
  "Mocking" module a la Jose's http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/
  """

  def pokemon(name) do
    case name do
      "caterpie" -> {:ok,
 %{"abilities" => [%{"ability" => %{"name" => "run-away",
        "url" => "http://pokeapi.co/api/v2/ability/50/"}, "is_hidden" => true,
      "slot" => 3},
    %{"ability" => %{"name" => "shield-dust",
        "url" => "http://pokeapi.co/api/v2/ability/19/"}, "is_hidden" => false,
      "slot" => 1}], "base_experience" => 39,
   "forms" => [%{"name" => "caterpie",
      "url" => "http://pokeapi.co/api/v2/pokemon-form/10/"}],
   "game_indices" => [%{"game_index" => 10,
      "version" => %{"name" => "white-2",
        "url" => "http://pokeapi.co/api/v2/version/22/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "black-2",
        "url" => "http://pokeapi.co/api/v2/version/21/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "white",
        "url" => "http://pokeapi.co/api/v2/version/18/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "black",
        "url" => "http://pokeapi.co/api/v2/version/17/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "soulsilver",
        "url" => "http://pokeapi.co/api/v2/version/16/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "heartgold",
        "url" => "http://pokeapi.co/api/v2/version/15/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "platinum",
        "url" => "http://pokeapi.co/api/v2/version/14/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "pearl",
        "url" => "http://pokeapi.co/api/v2/version/13/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "diamond",
        "url" => "http://pokeapi.co/api/v2/version/12/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "leafgreen",
        "url" => "http://pokeapi.co/api/v2/version/11/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "firered",
        "url" => "http://pokeapi.co/api/v2/version/10/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "emerald",
        "url" => "http://pokeapi.co/api/v2/version/9/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "sapphire",
        "url" => "http://pokeapi.co/api/v2/version/8/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "ruby",
        "url" => "http://pokeapi.co/api/v2/version/7/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "crystal",
        "url" => "http://pokeapi.co/api/v2/version/6/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "silver",
        "url" => "http://pokeapi.co/api/v2/version/5/"}},
    %{"game_index" => 10,
      "version" => %{"name" => "gold",
        "url" => "http://pokeapi.co/api/v2/version/4/"}},
    %{"game_index" => 123,
      "version" => %{"name" => "yellow",
        "url" => "http://pokeapi.co/api/v2/version/3/"}},
    %{"game_index" => 123,
      "version" => %{"name" => "blue",
        "url" => "http://pokeapi.co/api/v2/version/2/"}},
    %{"game_index" => 123,
      "version" => %{"name" => "red",
        "url" => "http://pokeapi.co/api/v2/version/1/"}}], "height" => 3,
   "held_items" => [], "id" => 10, "is_default" => true,
   "location_area_encounters" => "/api/v2/pokemon/10/encounters",
   "moves" => [%{"move" => %{"name" => "tackle",
        "url" => "http://pokeapi.co/api/v2/move/33/"},
      "version_group_details" => [%{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "x-y",
           "url" => "http://pokeapi.co/api/v2/version-group/15/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "xd",
           "url" => "http://pokeapi.co/api/v2/version-group/13/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "colosseum",
           "url" => "http://pokeapi.co/api/v2/version-group/12/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-white",
           "url" => "http://pokeapi.co/api/v2/version-group/11/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "platinum",
           "url" => "http://pokeapi.co/api/v2/version-group/9/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "diamond-pearl",
           "url" => "http://pokeapi.co/api/v2/version-group/8/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "firered-leafgreen",
           "url" => "http://pokeapi.co/api/v2/version-group/7/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "emerald",
           "url" => "http://pokeapi.co/api/v2/version-group/6/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "ruby-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/5/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "crystal",
           "url" => "http://pokeapi.co/api/v2/version-group/4/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "gold-silver",
           "url" => "http://pokeapi.co/api/v2/version-group/3/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "yellow",
           "url" => "http://pokeapi.co/api/v2/version-group/2/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "red-blue",
           "url" => "http://pokeapi.co/api/v2/version-group/1/"}}]},
    %{"move" => %{"name" => "string-shot",
        "url" => "http://pokeapi.co/api/v2/move/81/"},
      "version_group_details" => [%{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "x-y",
           "url" => "http://pokeapi.co/api/v2/version-group/15/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "xd",
           "url" => "http://pokeapi.co/api/v2/version-group/13/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "colosseum",
           "url" => "http://pokeapi.co/api/v2/version-group/12/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-white",
           "url" => "http://pokeapi.co/api/v2/version-group/11/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "platinum",
           "url" => "http://pokeapi.co/api/v2/version-group/9/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "diamond-pearl",
           "url" => "http://pokeapi.co/api/v2/version-group/8/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "firered-leafgreen",
           "url" => "http://pokeapi.co/api/v2/version-group/7/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "emerald",
           "url" => "http://pokeapi.co/api/v2/version-group/6/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "ruby-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/5/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "crystal",
           "url" => "http://pokeapi.co/api/v2/version-group/4/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "gold-silver",
           "url" => "http://pokeapi.co/api/v2/version-group/3/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "yellow",
           "url" => "http://pokeapi.co/api/v2/version-group/2/"}},
       %{"level_learned_at" => 1,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "red-blue",
           "url" => "http://pokeapi.co/api/v2/version-group/1/"}}]},
    %{"move" => %{"name" => "snore",
        "url" => "http://pokeapi.co/api/v2/move/173/"},
      "version_group_details" => [%{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "platinum",
           "url" => "http://pokeapi.co/api/v2/version-group/9/"}}]},
    %{"move" => %{"name" => "bug-bite",
        "url" => "http://pokeapi.co/api/v2/move/450/"},
      "version_group_details" => [%{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "x-y",
           "url" => "http://pokeapi.co/api/v2/version-group/15/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "black-white",
           "url" => "http://pokeapi.co/api/v2/version-group/11/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "heartgold-soulsilver",
           "url" => "http://pokeapi.co/api/v2/version-group/10/"}},
       %{"level_learned_at" => 15,
         "move_learn_method" => %{"name" => "level-up",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/1/"},
         "version_group" => %{"name" => "platinum",
           "url" => "http://pokeapi.co/api/v2/version-group/9/"}}]},
    %{"move" => %{"name" => "electroweb",
        "url" => "http://pokeapi.co/api/v2/move/527/"},
      "version_group_details" => [%{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "omega-ruby-alpha-sapphire",
           "url" => "http://pokeapi.co/api/v2/version-group/16/"}},
       %{"level_learned_at" => 0,
         "move_learn_method" => %{"name" => "tutor",
           "url" => "http://pokeapi.co/api/v2/move-learn-method/3/"},
         "version_group" => %{"name" => "black-2-white-2",
           "url" => "http://pokeapi.co/api/v2/version-group/14/"}}]}],
   "name" => "caterpie", "order" => 14,
   "species" => %{"name" => "caterpie",
     "url" => "http://pokeapi.co/api/v2/pokemon-species/10/"},
   "sprites" => %{"back_default" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10.png",
     "back_female" => nil,
     "back_shiny" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10.png",
     "back_shiny_female" => nil,
     "front_default" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
     "front_female" => nil,
     "front_shiny" => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png",
     "front_shiny_female" => nil},
   "stats" => [%{"base_stat" => 45, "effort" => 0,
      "stat" => %{"name" => "speed",
        "url" => "http://pokeapi.co/api/v2/stat/6/"}},
    %{"base_stat" => 20, "effort" => 0,
      "stat" => %{"name" => "special-defense",
        "url" => "http://pokeapi.co/api/v2/stat/5/"}},
    %{"base_stat" => 20, "effort" => 0,
      "stat" => %{"name" => "special-attack",
        "url" => "http://pokeapi.co/api/v2/stat/4/"}},
    %{"base_stat" => 35, "effort" => 0,
      "stat" => %{"name" => "defense",
        "url" => "http://pokeapi.co/api/v2/stat/3/"}},
    %{"base_stat" => 30, "effort" => 0,
      "stat" => %{"name" => "attack",
        "url" => "http://pokeapi.co/api/v2/stat/2/"}},
    %{"base_stat" => 45, "effort" => 1,
      "stat" => %{"name" => "hp",
        "url" => "http://pokeapi.co/api/v2/stat/1/"}}],
   "types" => [%{"slot" => 1,
      "type" => %{"name" => "bug",
        "url" => "http://pokeapi.co/api/v2/type/7/"}}], "weight" => 29}}
      end
  end

  def pokemon!(name) do
    {:ok, pokemon} = pokemon(name)
    pokemon
  end

  def pokemon_species(name) do
    :ok
  end

  def pokemon_species!(name) do
    {:ok, species} = pokemon_species(name)
    species
  end

end
